In [284]:
from typing import List, Dict, Tuple
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline
from torchvision import datasets
import torchvision.transforms as transforms
import numpy as np
dev = 'cpu'
if torch.cuda.is_available():
    dev = 'cuda:0'
print("Running on:",dev)
device = torch.device(dev)

Running on: cuda:0


# Quivers and quiver representations

The quiver class is designed to define an acyclic quiver with no double edges. The initial quiver is not required to have a bias vertex; such a vertex can be added with the ```add_bias()``` method.

The input list of vertices is meant to be a list of strings, one for each vertex. It is best to avoid the label ```bias``` among the vertices. 

The input list of edges is meant to be a tuple ```e = (e[0], e[1])``` where ```e[0]``` is the source and ```e[1]``` is the target. No double edges or loops are allowed.

In [285]:
class quiver:
    """Quiver class. Vertices are given as a list of strings. Edges are given as a list of pairs.
    
    Attributes and Methods.
    """
    def __init__(self, vertices : List[str], edges : List[Tuple[str]]):
        self.vertices = vertices
        # Add assert to check no repeated vertices
        # E.g. assert len(set(vertices)) == len(vertices)
        # Assert there is no bias initially, or if there is, it has the desired properties
        
        self.edges = edges
        # Add assert to check that edges is a list of pairs
        # First entry of the pair is the sourse, second is the target
        # Source and target of each edge should be in the vertex set      
        # Separate class for edges? vertices?
        
        # Get the sources and sinks
        sources = set(self.vertices)
        sinks = set(self.vertices)
        for e in self.edges:
            sources.discard(e[1])
            sinks.discard(e[0])
        self.sources = sources
        self.sinks = sinks
    
    # Check that the quiver is acyclic
    def check_acyclic(self):
        None
        # One way: find all sources, do depth-first search
        
    # Check that the vertices are in topological order    
    def check_top_order(self):
        indices = {}
        for i,v in enumerate(self.vertices):
            indices[v] = i
        return all([indices[e[0]] <  indices[e[1]] for e in self.edges])
        
    # Get the incoming edges for every vertex
    def get_incoming(self, vertex):
        assert vertex in self.vertices, "No such vertex found"
        return [e for e in self.edges if e[1] == vertex]
        # Can get the incoming neighbors as [e[1] for e in self.get_incoming(vertex)]
        
    # Add a bias vertex. Considering alternatives to this ... 
    def add_bias(self):
        # Add bias vertex. This will not disturb the topological order.
        for v in self.vertices:
            if v not in self.sources:
                self.edges.append(('bias', v))
        self.vertices = ['bias'] + self.vertices
        return
    
    ######
    # Check if a vertex is a sink (Don't really need this any more)
    def is_sink(self, vertex):
        assert vertex in self.vertices, "No such vertex found"
        return all([e[0] != vertex for e in self.edges])
    


In [289]:
class quiver_rep:
    """Quiver representation class. Input a quiver with dimension vector and a matrix for each edge."""
    def __init__(self, quiver: quiver, dims: Dict[str,int], matrices: Dict[str, np.array]):
        self.quiver = quiver
        self.dims = dims
        self.matrices = matrices
        
        # Check the dimension vector
        assert len(dims) == len(self.quiver.vertices), "Inappropriate dimension vector"
        for v in dims:
            assert v in self.quiver.vertices, "Inappropriate dim vector"
            assert isinstance(dims[v], int) and dims[v] >=0, "Dimension needs to be a positive integer"
        assert dims['bias'] == 1, "Dimension at bias needs to be 1"

            
        # Check the matrices
        assert len(matrices) == len(self.quiver.edges), "Matrices error"
        for e in matrices:
            assert e in self.quiver.edges, "Matrices error"
            assert isinstance(matrices[e], np.ndarray), "Matrices error" # May need fixing
            assert np.shape(matrices[e]) == (dims[e[1]], dims[e[0]]), "Dimension error"
            
            
    # Compute the reduced dimension vector
    def comp_dims_red(self) -> Dict:
        
        assert self.quiver.check_top_order(), "Order of the vertices is not topological"

        dims_red = {}
        for i in self.quiver.vertices:
            if i == 'bias' or i in self.quiver.sources or i in self.quiver.sinks:
                dims_red[i] = self.dims[i]
            else:
                incoming = self.quiver.get_incoming(i)
                dims_red[i] = min(self.dims[i], sum([dims_red[e[0]] for e in incoming]) )

                    
        self.dims_red = dims_red        
        return dims_red
    
    
    # Auxiliary function
    def padzeros(self, M, newrows, newcols = None):
        oldrows, oldcols = M.shape
        if newcols == None:
            newcols = oldcols
        return np.pad(M,((0,newrows-oldrows),(0,newcols-oldcols)),mode="constant")
 
    
    # QR dimensional reduction algorithm
    def QRDimRed(self, verbose : bool = False ):
        dims = self.dims
        matrices = self.matrices
        quiver = self.quiver
        vertices = quiver.vertices
        edges = quiver.edges

        # Check that vertices are in a topological order
        assert quiver.check_top_order(), "Order of the vertices is not topological"

        # Compute the reduced dimension vector
        dims_red = self.comp_dims_red()
        # print(dims, dims_red)

        # Q = dictionary mapping each vertex to an orthogonal matrix
        Q = {}

        # Vmatrices = matrices of the reduced representation V, mapping each edge to a matrix
        Vmatrices = {}

        if verbose:
            print(quiver.edges)
            print(quiver.vertices)

        for i in vertices:
            incoming = quiver.get_incoming(i)

            # Case of a source vertex
            if incoming == []:
                Q[i] = np.eye(dims[i])

            # Case of a hidden vertex    
            elif i not in quiver.sinks:

                # Compute the matrix to be QR-decomposed
                M = np.array([])
                for e in incoming:
                    # Transform weights on incoming edges
                    Qj = Q[e[0]]
                    Me = matrices[e] @ Qj[:,:dims_red[e[0]]]
                    if np.shape(M) == (0,):
                        M = Me
                    else:
                        M = np.hstack((M, Me))

                Q[i], R = np.linalg.qr(M, mode="complete")

                # Case of reduction 
                if dims_red[i] < dims[i]: 
                    R = R[:dims_red[i]]

                # Process and add to the dictionaries
                for e in incoming:                       
                    # Extract V_e from R_i for all incoming edges e
                    Vmatrices[e] = R[:,:dims_red[e[0]]]
                    R = R[:,dims_red[e[0]]:]

            # Case of a sink (no reduction)
            else:
                Q[i] = np.eye(dims[i])
                for e in incoming:
                    # Transform weights on incoming edges
                    Qj = Q[e[0]]
                    Vmatrices[e] = matrices[e] @ Qj[:,:dims_red[e[0]]]                


        # Make V into a representation
        V = quiver_rep(quiver, dims_red, Vmatrices)

        # Verify that V is a subrepresentation of Q^{-1} W  
        for e in quiver.edges:
            Qi = Q[e[0]]
            Qj = Q[e[1]]
            max_diff = np.max(np.abs(np.transpose(Qj) @ matrices[e] @ Qi[:,:dims_red[e[0]]] 
                         - self.padzeros(Vmatrices[e], dims[e[1]])))
            assert max_diff < 1e-10, "Error in the algorithm"

        return Q, V
    
    
    def reduced_representation(self, verbose : bool = False ):
        return self.QRDimRed(verbose)[1]
                
    def transformed_representation(self):
        Q, V = self.QRDimRed()
        transformed_mat_dict = {}
        for e in self.quiver.edges:
            breakpoint()
            transformed_mat_dict[e] = np.transpose(Q[e[1]]) @ self.matrices[e] @ Q[e[0]]
        
        Q_inv_W = quiver_rep(self.quiver, self.dims, transformed_mat_dict)
        
        return Q_inv_W

### Linear Feedforward Function

In [ ]:
# Linear feedforward function, ignoring biases
# Might turn out not to be super necessary

def lin_ff(W : quiver_rep) -> np.array:
    dims = W.dims
    matrices = W.matrices
    quiver = W.quiver
    vertices = quiver.vertices
    edges = quiver.edges
    
    assert quiver.check_top_order(), "Order of the vertices is not topological"
    
    # Dictionary for partial feedforward functions:
    partial = {}
    input_dim = 0
    # input_dim = sum( [dims[i] for i in quiver.sources])
    
    for i in quiver.vertices:
        incoming = quiver.get_incoming(i)
        
        # Case of a source
        if i in quiver.sources:
            
            # Update matrices already defined
            for j in partial:
                partial[j] = np.hstack((partial[j], np.zeros((dims[j],dims[i]))))
                
            # Define the new matrix as a projection matrix
            if input_dim == 0:
                partial[i] = np.eye(dims[i])
            else:
                partial[i] = np.hstack((np.zeros((dims[i], input_dim)), np.eye(dims[i])))
            input_dim += dims[i]

        # Case of a hidden vertex or a sink
        else:
            
            # Compute the matrix to be added
            A = np.zeros((dims[i], input_dim))
            for e in incoming:
                # Ignore biases for now
                if e[0] != 'bias':
                    A += matrices[e] @ partial[e[0]]
            partial[i] = A
         
    # Compute the final output matrix by stacking the matrices for sinks
    result = np.array([])
    for i in quiver.sinks:
        if np.shape(result) == (0,):
            result = partial[i]
        else:
            result = np.vstack((result, partial[i]))
                        
    return result

# Dimensional reduction algorithm

In [178]:
# Auxiliary function

def padzeros(M,newrows,newcols = None):
    oldrows, oldcols = M.shape
    if newcols == None:
        newcols = oldcols
    return np.pad(M,((0,newrows-oldrows),(0,newcols-oldcols)),mode="constant")

In [179]:
# QR dimensional reduction algorithm
# This is incorporated in the quiver_rep class

def QRDimRed(W : quiver_rep, verbose : bool = False ):
    dims = W.dims
    matrices = W.matrices
    quiver = W.quiver
    vertices = quiver.vertices
    edges = quiver.edges
    
    # Check that vertices are in a topological order
    assert quiver.check_top_order(), "Order of the vertices is not topological"
    
    # Compute the reduced dimension vector
    dims_red = W.comp_dims_red()
    # print(dims, dims_red)
    
    # Q = dictionary mapping each vertex to an orthogonal matrix
    Q = {}
    
    # Vmatrices = matrices of the reduced representation V, mapping each edge to a matrix
    Vmatrices = {}
    
    if verbose:
        print(quiver.edges)
        print(quiver.vertices)
    
    for i in vertices:
        incoming = quiver.get_incoming(i)
        
        # Case of a source vertex
        if incoming == []:
            Q[i] = np.eye(dims[i])
            
        # Case of a hidden vertex    
        elif i not in quiver.sinks:
            
            # Compute the matrix to be QR-decomposed
            M = np.array([])
            for e in incoming:
                # Transform weights on incoming edges
                Qj = Q[e[0]]
                Me = matrices[e] @ Qj[:,:dims_red[e[0]]]
                if np.shape(M) == (0,):
                    M = Me
                else:
                    M = np.hstack((M, Me))
                    
            Q[i], R = np.linalg.qr(M, mode="complete")

            # Case of reduction 
            if dims_red[i] < dims[i]: 
                R = R[:dims_red[i]]
                
            # Process and add to the dictionaries
            for e in incoming:                       
                # Extract V_e from R_i for all incoming edges e
                Vmatrices[e] = R[:,:dims_red[e[0]]]
                R = R[:,dims_red[e[0]]:]
                
        # Case of a sink (no reduction)
        else:
            Q[i] = np.eye(dims[i])
            for e in incoming:
                # Transform weights on incoming edges
                Qj = Q[e[0]]
                Vmatrices[e] = matrices[e] @ Qj[:,:dims_red[e[0]]]                

    
    # Make V into a representation
    V = quiver_rep(quiver, dims_red, Vmatrices)

    # Verify that V is a subrepresentation of Q^{-1} W  
    for e in quiver.edges:
        Qi = Q[e[0]]
        Qj = Q[e[1]]
        max_diff = np.max(np.abs(np.transpose(Qj) @ matrices[e] @ Qi[:,:dims_red[e[0]]] 
                     - padzeros(Vmatrices[e], dims[e[1]])))
        assert max_diff < 1e-10, "Error in the algorithm"

    return Q, V

# Example 1

In [155]:
# EXAMPLE
# Quiver with skip connections and no bias

vertex_list = ['a', 'b', 'c', 'd']
edge_list = [('a', 'b'), ('a','c'), ('b','c'), ('c', 'd')]

quiv_ex = quiver(vertex_list, edge_list)
# print(Q.vertices, Q.edges)

# Test the methods
print(quiv_ex.get_incoming('a'), quiv_ex.get_incoming('b'), quiv_ex.get_incoming('c'), quiv_ex.get_incoming('d'))
print(quiv_ex.is_sink('a'), quiv_ex.is_sink('b'), quiv_ex.is_sink('c'), quiv_ex.is_sink('d'))
print(quiv_ex.check_top_order())
print(quiv_ex.sources)
quiv_ex.add_bias()
print(quiv_ex.vertices)
print(quiv_ex.edges)

[] [('a', 'b')] [('a', 'c'), ('b', 'c')] [('c', 'd')]
False False False True
True
{'a'}
['bias', 'a', 'b', 'c', 'd']
[('a', 'b'), ('a', 'c'), ('b', 'c'), ('c', 'd'), ('bias', 'b'), ('bias', 'c'), ('bias', 'd')]


In [10]:
# Representation of this quiver

dim_vector = {'bias' : 1, 'a': 2, 'b': 4, 'c': 8, 'd': 2 }

maps = {('a', 'b') : np.random.rand(4, 2), 
        ('a', 'c') : np.random.rand(8, 2), 
        ('b', 'c') : np.random.rand(8, 4),
        ('c', 'd') : np.random.rand(2, 8),
        ('bias', 'b') : np.random.rand(4, 1),
        ('bias', 'c') : np.random.rand(8, 1),
        ('bias', 'd') : np.random.rand(2, 1)}

ex_rep = quiver_rep(quiv_ex, dim_vector, maps)
print(ex_rep.comp_dims_red())

{'bias': 1, 'a': 2, 'b': 3, 'c': 6, 'd': 2}


In [11]:
# Check the algorithm

Q_ex ,V_ex = QRDimRed(ex_rep)
print(ex_rep.comp_dims_red())
print([np.shape(Q_ex[i]) for i in Q_ex])
print([np.shape(V_ex.matrices[e]) for e in V_ex.matrices])

{'bias': 1, 'a': 2, 'b': 3, 'c': 6, 'd': 2}
[(1, 1), (2, 2), (4, 4), (8, 8), (2, 2)]
[(3, 2), (3, 1), (6, 2), (6, 3), (6, 1), (2, 6), (2, 1)]


In [12]:
lin_ff(ex_rep)

array([[7.84656088, 7.27676386],
       [6.16817118, 5.87194995]])

In [13]:
ex_rep.matrices[('c','d')] @ ( ex_rep.matrices[('a','c')] + ex_rep.matrices[('b','c')] @ ex_rep.matrices[('a','b')] )

array([[7.84656088, 7.27676386],
       [6.16817118, 5.87194995]])

In [14]:
lin_ff(V_ex)

array([[7.84656088, 7.27676386],
       [6.16817118, 5.87194995]])

# Example 2

In [287]:
# EXAMPLE
# Quiver with multiple inputs and outputs

vertex_list2 = ['a', 'b', 'c', 'd', 'e']
edge_list2 = [('a', 'c'), ('b','c'), ('c','d'), ('c', 'e')]

quiv_ex2 = quiver(vertex_list2, edge_list2)
# print(Q.vertices, Q.edges)

# Test the methods
print(quiv_ex2.get_incoming('a'), quiv_ex2.get_incoming('b'), quiv_ex2.get_incoming('c'), 
      quiv_ex2.get_incoming('d'), quiv_ex2.get_incoming('e'))
print(quiv_ex2.is_sink('a'), quiv_ex2.is_sink('b'), quiv_ex2.is_sink('c'), 
      quiv_ex2.is_sink('d'), quiv_ex2.is_sink('e'))
print(quiv_ex2.check_top_order())
print(quiv_ex2.sources)
quiv_ex2.add_bias()
print(quiv_ex2.vertices)
print(quiv_ex2.edges)

[] [] [('a', 'c'), ('b', 'c')] [('c', 'd')] [('c', 'e')]
False False False True True
True
{'a', 'b'}
['bias', 'a', 'b', 'c', 'd', 'e']
[('a', 'c'), ('b', 'c'), ('c', 'd'), ('c', 'e'), ('bias', 'c'), ('bias', 'd'), ('bias', 'e')]


In [181]:
# Representation of this quiver

dim_vector2 = {'bias' : 1, 'a': 1, 'b': 2, 'c': 8, 'd': 2 , 'e': 6}

maps2 = {('a', 'c') : np.random.rand(8, 1), 
        ('b', 'c') : np.random.rand(8, 2), 
        ('c', 'd') : np.random.rand(2, 8),
        ('c', 'e') : np.random.rand(6, 8),
        ('bias', 'c') : np.random.rand(8, 1),
        ('bias', 'd') : np.random.rand(2, 1),
        ('bias', 'e') : np.random.rand(6, 1)}

ex_rep2 = quiver_rep(quiv_ex2, dim_vector2, maps2)
print(ex_rep2.comp_dims_red())

{'bias': 1, 'a': 1, 'b': 2, 'c': 4, 'd': 2, 'e': 6}


In [182]:
# Check the algorithm

Q_ex2 ,V_ex2 = QRDimRed(ex_rep2)
print(ex_rep2.comp_dims_red())
print([np.shape(Q_ex2[i]) for i in Q_ex2])
print([np.shape(V_ex2.matrices[e]) for e in V_ex2.matrices])

{'bias': 1, 'a': 1, 'b': 2, 'c': 4, 'd': 2, 'e': 6}
[(1, 1), (1, 1), (2, 2), (8, 8), (2, 2), (6, 6)]
[(4, 1), (4, 2), (4, 1), (2, 4), (2, 1), (6, 4), (6, 1)]


In [183]:
lin_ff(ex_rep2)

array([[2.42634553, 2.59075974, 1.54111815],
       [1.24592817, 1.21881054, 0.74666681],
       [2.19768811, 2.39054329, 1.50132817],
       [2.19165735, 2.38215029, 1.68995036],
       [2.59759706, 2.41261937, 1.596163  ],
       [1.95618287, 2.37873148, 1.21171795],
       [1.73291241, 1.93242686, 1.04614513],
       [2.2746769 , 2.55232039, 1.33372596]])

In [184]:
lin_ff(V_ex2)

array([[2.42634553, 2.59075974, 1.54111815],
       [1.24592817, 1.21881054, 0.74666681],
       [2.19768811, 2.39054329, 1.50132817],
       [2.19165735, 2.38215029, 1.68995036],
       [2.59759706, 2.41261937, 1.596163  ],
       [1.95618287, 2.37873148, 1.21171795],
       [1.73291241, 1.93242686, 1.04614513],
       [2.2746769 , 2.55232039, 1.33372596]])

# Quiver Neural Networks

In [185]:
class RadAct(nn.Module):
    def __init__(self, eta = F.relu):
        super().__init__()
        self.eta = eta
        self.shift = 0 
        # Add internal bias/shift later
        
    def forward(self,x):
        # x: [Batch x Channel]
        # Radial activations
        r = torch.linalg.norm(x, dim=-1) 
        if torch.min(r) < 1e-6:
            r += 1e-6
        scalar = self.eta(r + self.shift) / r
        return x * scalar.unsqueeze(-1)   

In [272]:
class QuiverNN(nn.Module):
    
    def __init__(self, eta: float , quiver: quiver, dims: Dict[str,int] ):
        super().__init__()
        self.eta = eta
        self.quiver = quiver
        self.dims = dims
        self.matrices = nn.ModuleDict()
        for e in quiver.edges:
            self.matrices[self.edge_tup_to_str(e)] = nn.Linear(self.dims[e[0]], self.dims[e[1]], bias = False)
        
        assert quiver.check_top_order(), "Vertices not in topological order."
        
        self.act = RadAct(self.eta)
        #self.quiver_rep = quiver_rep()
        
        # Assert statement to check that dims is a dimension vector for Q
        
        # Reduced dimension vector
    
    def edge_tup_to_str(self,e):
        (t,h) = e
        return t + " to " + h

    def edge_str_to_tup(self,e):
        t,to,h = e.split()
        return (t,h)

    def forward(self, x, non_linear = True):
        
        #Initialize Data Flow
        h = {}
        h['bias'] = torch.tensor(1.0)
        for v in self.quiver.sources:
            h[v] = x[v]
            batch_size = x[v].shape[0]
        
        #Assert batchsize is same for all sources 
        
        for v in self.quiver.vertices:
            if v not in self.quiver.sources:
                h[v] = torch.zeros(batch_size,self.dims[v])
                for e in self.quiver.get_incoming(v):
                    e_lin = self.matrices[self.edge_tup_to_str(e)]
                    h[e[1]] += e_lin(h[e[0]])
                if non_linear:
                    h[v] = self.act(h[v])
        
        out = {}
        for v in self.quiver.sinks:
            out[v] = h[v]
            
        return out
            
    
    def set_weights(self, new_weights: quiver_rep):
        assert new_weights.quiver == self.quiver, "weights have different quiver"
        
        for e in self.quiver.edges:
            self.matrices[self.edge_tup_to_str(e)].weight = \
                torch.nn.Parameter(torch.tensor(new_weights.matrices[e],dtype = torch.float))
        self.dims = new_weights.dims
    
    def set_activation_biases(self, new_biases: List[float]):    
        None

    def export_weights(self) -> quiver_rep:
        quiver_rep_matrix_dict = {}
        for e in self.quiver.edges:
            quiver_rep_matrix_dict[e] = self.matrices[self.edge_tup_to_str(e)].weight.detach().cpu().numpy()
        return quiver_rep(self.quiver, self.dims, quiver_rep_matrix_dict)
    
    def export_activation_biases(self) -> List[float]:
        None
    
    def export_reduced_weights(self) -> quiver_rep:
        exported_rep = self.export_weights()
        return exported_rep.reduced_representation()
    
    def transformed_network(self):
        exported_rep = self.export_weights()
        rep_transformed = exported_rep.transformed_representation()
        net_trans = QuiverNN(self.eta, self.quiver, self.dims)
        net_trans.set_weights(rep_transformed)
        #net_trans.set_activation_biases(self.export_activation_biases())
        return net_trans
        
    def reduced_network(self):
        reduced_rep = self.export_reduced_weights()
        net_reduced = QuiverNN(self.eta, self.quiver, reduced_rep.dims)
        net_reduced.set_weights(reduced_rep)
        #net_trans.set_activation_biases(self.export_activation_biases())
        return net_reduced

In [273]:
vertex_list2 = ['a', 'b', 'c', 'd', 'e']
edge_list2 = [('a', 'c'), ('b','c'), ('c','d'), ('c', 'e')]
dim_vector2 = {'bias' : 1, 'a': 1, 'b': 2, 'c': 8, 'd': 2 , 'e': 6}
quiv_ex2 = quiver(vertex_list2, edge_list2)
quiv_ex2.add_bias()

quiverNN = QuiverNN(eta = F.relu, quiver = quiv_ex2, dims = dim_vector2)

In [274]:
x = {'a': torch.tensor([[1.0]]),'b': torch.tensor([[1.0,1.0]])}
quiverNN(x)

{'d': tensor([[-0.3187, -0.0885]], grad_fn=<MulBackward0>),
 'e': tensor([[ 0.0246,  0.6616, -0.3427, -0.3384,  0.5883,  0.3246]],
        grad_fn=<MulBackward0>)}

In [275]:
# Representation of this quiver

maps2 = {('a', 'c') : np.random.rand(8, 1), 
        ('b', 'c') : np.random.rand(8, 2), 
        ('c', 'd') : np.random.rand(2, 8),
        ('c', 'e') : np.random.rand(6, 8),
        ('bias', 'c') : np.random.rand(8, 1),
        ('bias', 'd') : np.random.rand(2, 1),
        ('bias', 'e') : np.random.rand(6, 1)}

ex_rep2 = quiver_rep(quiv_ex2, dim_vector2, maps2)
print(ex_rep2.comp_dims_red())

quiverNN.set_weights(ex_rep2)

{'bias': 1, 'a': 1, 'b': 2, 'c': 4, 'd': 2, 'e': 6}


In [276]:
quiverNN.export_weights()

In [277]:
quiverNN.export_reduced_weights()

In [278]:
quiverNN.export_weights().comp_dims_red()

{'bias': 1, 'a': 1, 'b': 2, 'c': 4, 'd': 2, 'e': 6}

In [279]:
red_quiverNN = quiverNN.reduced_network()
red_quiverNN

QuiverNN(
  (matrices): ModuleDict(
    (a to c): Linear(in_features=1, out_features=4, bias=False)
    (b to c): Linear(in_features=2, out_features=4, bias=False)
    (c to d): Linear(in_features=4, out_features=2, bias=False)
    (c to e): Linear(in_features=4, out_features=6, bias=False)
    (bias to c): Linear(in_features=1, out_features=4, bias=False)
    (bias to d): Linear(in_features=1, out_features=2, bias=False)
    (bias to e): Linear(in_features=1, out_features=6, bias=False)
  )
  (act): RadAct()
)

In [280]:
red_quiverNN = quiverNN.reduced_network()
x = {'a': torch.tensor([[1.0]]),'b': torch.tensor([[1.0,1.0]])}
red_quiverNN(x)

{'d': tensor([[5.7304, 6.0896]], grad_fn=<MulBackward0>),
 'e': tensor([[7.7161, 5.1292, 7.7448, 7.1004, 3.9315, 7.0689]],
        grad_fn=<MulBackward0>)}

In [283]:
quiverNN.transformed_network()

> <ipython-input-282-3ff000e5f32d>(139)transformed_representation()
    137         for e in self.quiver.edges:
    138             breakpoint()
--> 139             transformed_mat_dict[e] = np.transpose(Q[e[1]]) @ V.matrices[e] @ Q[e[0]]
    140 
    141         Q_inv_W = quiver_rep(self.quiver, self.dims, transformed_mat_dict)

ipdb> e
('a', 'c')
ipdb> Q[e[1]]
array([[-0.39413409, -0.3821514 , -0.0205056 , -0.00763372, -0.78661091,
        -0.06475792, -0.18277059,  0.20441252],
       [-0.24874292, -0.27595677,  0.09833052, -0.00526985,  0.35620878,
         0.26617612,  0.31067713,  0.74700968],
       [-0.57600779, -0.31349274, -0.01815573,  0.11619732,  0.38001785,
         0.30011181, -0.34794283, -0.44784039],
       [-0.32810272,  0.10788731,  0.39899106, -0.06215983,  0.23568079,
        -0.78812304, -0.16636973,  0.11527785],
       [-0.20923412,  0.47081375,  0.3658155 ,  0.71780676, -0.17385344,
         0.21108317,  0.09979427,  0.0273486 ],
       [-0.17161347,  0.407040

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 8)

# Scraps

In [ ]:
class vertex:
    def __init__(self):
        None

In [ ]:
a = vertex()

In [ ]:
# Troubleshooting

W1 = np.random.rand(4, 2)
print(type(W1))
print(isinstance(W1, np.ndarray))

In [ ]:
a = np.random.rand(4,2)
b = np.random.rand(4,4)
a, b

In [ ]:
c = np.hstack((a,b))
np.shape(c)

In [ ]:
b

In [ ]:
b[:,:2]

In [ ]:
b[:,2:]

In [ ]:
np.shape(b[:,:2])

In [ ]:
np.shape(np.array([]))